spring:
  application:
    name: Api-Gateway
  config:
    import: configserver:http://localhost:8085

  cloud:
    gateway:
      routes:
        - id: User-Service
          uri: lb://User-Service
          predicates:
            - Path=/users/**

        - id: Hotel-Service
          uri: lb://Hotel-Service
          predicates:
            - Path=/hotels/**,/staffs/**

        - id: Rating-Service
          uri: lb://Rating-Service
          predicates:
            - Path=/ratings/**


server:
  port: 8084

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8762/eureka
