server :
  port : 8082

spring :
  datasource :
    url : jdbc:mysql://localhost:3306/microservice
    username : root
    password : cdac

  jpa :
    hibernate :
      ddl-auto : update
    show-sql : true

