server :
  port : 8082

spring :
  datasource :
    url : jdbc:mysql://localhost:3306/hotelservicedatabase
    username : root
    password : cdac

  jpa :
    hibernate :
      ddl-auto : update
    show-sql : true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8762/eureka
